export const mockFeedbacks = [
  {
    id: 1,
    name: "Alice",
    type: "Idea",
    text: "It would be great to have a dark mode toggle on the homepage.",
    date: "2026-01-09",
  },
  {
    id: 2,
    name: "Bob",
    type: "Bug",
    text: "The submit button sometimes doesn’t respond on mobile devices.",
    date: "2026-01-08",
  },
  {
    id: 3,
    name: null,
    type: "Praise",
    text: "I love how fast and simple the feedback flow is!",
    date: "2026-01-07",
  },
  {
    id: 4,
    name: "Charlie",
    type: "Idea",
    text: "Maybe add categories or tags for feedback, so it’s easier to browse.",
    date: "2026-01-05",
  },
  {
    id: 5,
    name: null,
    type: "Bug",
    text: "The page scroll jumps a bit when you open the dropdown menu.",
    date: "2026-01-04",
  },
  {
    id: 6,
    name: "Diana",
    type: "Praise",
    text: "Really intuitive design, loved leaving feedback!",
    date: "2026-01-02",
  },
  {
    id: 7,
    name: "Eve",
    type: "Idea",
    text: "A search bar for previous feedbacks could be really helpful.",
    date: "2026-01-01",
  },
  {
    id: 8,
    name: null,
    type: "Bug",
    text: "Some text overlaps the submit button on smaller screens.",
    date: "2025-12-30",
  },
  {
    id: 9,
    name: "Frank",
    type: "Praise",
    text: "I appreciate the clean design and clear instructions!",
    date: "2025-12-29",
  },
  {
    id: 10,
    name: "Grace",
    type: "Idea",
    text: "Maybe add a confirmation modal after sending feedback.",
    date: "2025-12-28",
  },
  {
    id: 11,
    name: null,
    type: "Bug",
    text: "Dropdown sometimes closes when clicking inside on mobile.",
    date: "2025-12-27",
  },
  {
    id: 12,
    name: "Henry",
    type: "Praise",
    text: "Fast loading times and smooth animations, great job!",
    date: "2025-12-26",
  },
];
